# Generated by Django 5.2 on 2025-05-02 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_clothingitem_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='is_paid',
            new_name='is_confirmed',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='store.clothingitem'),
        ),
    ]
