# Generated by Django 5.2.1 on 2025-05-12 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothingitem',
            name='category',
        ),
        migrations.AddField(
            model_name='clothingitem',
            name='description',
            field=models.TextField(default='Опис не вказано'),
        ),
    ]
