# Generated by Django 5.2.1 on 2025-05-12 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_clothingitem_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothingitem',
            name='category',
            field=models.CharField(default='Невизначено', max_length=100),
            preserve_default=False,
        ),
    ]
